name: Main

on: 
  push:
    branches: [ main ]

jobs:
  init:
    runs-on: ubuntu-latest
    container: node:18.10.0
    services: 
      postgres: 
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
    strategy:
      matrix: 
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup environment variables 1/2
        run: |
          cd scretch-cloud-server
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "API_CLIENT_URL=${{ secrets.API_CLIENT_URL }}" >> .env
          echo "APP_PREFIX=${{ secrets.APP_PREFIX }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "POSTGRES_URI=${{ secrets.POSTGRES_URI }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "ACCESS_TOKEN_EXPIRES=${{ secrets.ACCESS_TOKEN_EXPIRES }}" >> .env
      - name: Setup environment variables 2/2
        run: |
          cd scretch-cloud-server
          echo "REFRESH_TOKEN_EXPIRES=${{ secrets.REFRESH_TOKEN_EXPIRES }}" >> .env
          echo "REFRESH_TOKEN_COOKIE_NAME=${{ secrets.REFRESH_TOKEN_COOKIE_NAME }}" >> .env
          echo "REFRESH_TOKEN_COOKIE_EXPIRES=${{ secrets.REFRESH_TOKEN_COOKIE_EXPIRES }}" >> .env
          echo "SWAGGER_TITLE=${{ secrets.SWAGGER_TITLE }}" >> .env
          echo "SWAGGER_DESCRIPTION=${{ secrets.SWAGGER_DESCRIPTION }}" >> .env
          echo "SWAGGER_PATH=${{ secrets.SWAGGER_PATH }}" >> .env
          echo "USERS_DEFAULT_STORAGE_LIMIT=${{ secrets.USERS_DEFAULT_STORAGE_LIMIT }}" >> .env
          echo "USERS_PRO_STORAGE_LIMIT=${{ secrets.USERS_PRO_STORAGE_LIMIT }}" >> .env
          echo "STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }}" >> .env
          echo "STRIPE_PRO_SUBSCRIPTION_PRICE=${{ secrets.STRIPE_PRO_SUBSCRIPTION_PRICE }}" >> .env
      - name: Install project dependencies
        run: cd scretch-cloud-server && npm install
      - name: Prisma push
        run: cd scretch-cloud-server && npx prisma db push
      - name: Run Unit tests
        run: cd scretch-cloud-server && npm run test
      - name: Run E2E tests
        run: cd scretch-cloud-server && npm run test:e2e